In [1]:
import pandas as pd 

In [4]:
dataset=pd.read_csv('spam.csv',encoding='latin1')

In [5]:
dataset

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [8]:
# Drop the column by its name
dataset.drop('Unnamed: 2', axis=1, inplace=True)


In [10]:
dataset.drop('Unnamed: 4', axis=1, inplace=True)


In [11]:
dataset

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [12]:
dataset['v2']

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object

In [15]:
dataset.columns

Index(['v1', 'v2'], dtype='object')

In [17]:
dataset['spam']=dataset['v1'].apply(lambda x: 1 if x=='spam'else 0)

In [18]:
dataset.head()

v1                                                 v2  spam
0   ham  Go until jurong point, crazy.. Available only ...     0
1   ham                      Ok lar... Joking wif u oni...     0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3   ham  U dun say so early hor... U c already then say...     0
4   ham  Nah I don't think he goes to usf, he lives aro...     0

In [20]:
new_data = pd.read_csv('spam.csv',encoding='latin1')

In [23]:
new_data.drop('Unnamed: 4', axis=1, inplace=True)

In [24]:
new_data['v1'].replace({'spam':1,'ham':0},inplace=True)

C:\Users\kumaw\AppData\Local\Temp\ipykernel_21348\1935124976.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_data['v1'].replace({'spam':1,'ham':0},inplace=True)


In [72]:
new_data['v2'][2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [73]:
new_data

v1                                                 v2
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...
...   ..                                                ...
5567   1  This is the 2nd time we have tried 2 contact u...
5568   0              Will Ì_ b going to esplanade fr home?
5569   0  Pity, * was in mood for that. So...any other s...
5570   0  The guy did some bitching but I acted like i'd...
5571   0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [26]:
new_data.shape

(5572, 2)

In [27]:
# trainig test split 
import sklearn 

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x_train , x_test , y_train , y_test=train_test_split(dataset.v2,dataset.spam ,test_size=0.25)

In [30]:
x_train.shape

(4179,)

In [31]:
x_train[:4]

314             You made my day. Do have a great day too.
4378                 How are you. Just checking up on you
3391                      What r u cooking me for dinner?
4414    Yeah I should be able to, I'll text you when I...
Name: v2, dtype: object

##### create bag to words 

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

In [33]:
v =CountVectorizer()

In [58]:
x_train_cv=v.fit_transform(x_train.values)
x_test_cv = v.transform(x_test.values)

In [37]:
x_train_cv.toarray()[:4][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [38]:
x_train_cv.shape

(4179, 7445)

In [42]:
v.get_feature_names_out()[1712]

'childish'

In [43]:
v.vocabulary_

{'you': 7393,
 'made': 4133,
 'my': 4486,
 'day': 2090,
 'do': 2271,
 'have': 3215,
 'great': 3097,
 'too': 6684,
 'how': 3372,
 'are': 1001,
 'just': 3724,
 'checking': 1685,
 'up': 6880,
 'on': 4745,
 'what': 7168,
 'cooking': 1918,
 'me': 4233,
 'for': 2816,
 'dinner': 2228,
 'yeah': 7364,
 'should': 5884,
 'be': 1206,
 'able': 709,
 'to': 6650,
 'll': 3995,
 'text': 6508,
 'when': 7175,
 'ready': 5387,
 'meet': 4252,
 'yun': 7413,
 'ah': 822,
 'the': 6535,
 'ubi': 6817,
 'one': 4750,
 'say': 5697,
 'if': 3453,
 'ì_': 7436,
 'wan': 7066,
 'call': 1539,
 'by': 1522,
 'tomorrow': 6672,
 '67441233': 548,
 'look': 4031,
 'irene': 3583,
 'ere': 2515,
 'only': 4756,
 'got': 3060,
 'bus8': 1503,
 '22': 333,
 '65': 544,
 '61': 534,
 '66': 546,
 '382': 420,
 'cres': 1984,
 'tech': 6463,
 'park': 4885,
 '6ph': 565,
 '1st': 311,
 '5wkg': 529,
 'days': 2091,
 'lets': 3921,
 'use': 6915,
 'it': 3603,
 'next': 4578,
 'week': 7132,
 'princess': 5204,
 'watching': 7095,
 'tv': 6791,
 'lor': 4042,
 

In [45]:
x_train_np=x_train_cv.toarray()

In [47]:
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [48]:
import numpy as np 

In [49]:
np.where(x_train_np[0]!=0)

(array([2090, 2271, 3097, 3215, 4133, 4486, 6684, 7393], dtype=int64),)

In [50]:
from sklearn.naive_bayes import MultinomialNB

In [51]:
obj =MultinomialNB()

In [52]:
obj.fit(x_train_np,y_train)

MultinomialNB()

In [53]:
obj.score(x_train_np,y_train)

0.9952141660684374

In [57]:
x_test.shape , x_train.shape, y_test.shape , y_train.shape 

((1393,), (4179,), (1393,), (4179,))

In [60]:
pred=obj.predict(x_test_cv)

In [61]:
print(pred)

[0 1 0 ... 1 0 0]


In [62]:
from sklearn.metrics import classification_report

In [64]:
output =classification_report(y_test,pred)

In [66]:
print(output)

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1192
           1       0.97      0.93      0.95       201

    accuracy                           0.99      1393
   macro avg       0.98      0.96      0.97      1393
weighted avg       0.99      0.99      0.99      1393



In [71]:
message = {"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."}
message=v.transform(message)
print(obj.predict(message))

[0]


In [74]:
message = {"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"}
message=v.transform(message)
print(obj.predict(message))

[1]
