### BOW >>>>>>>>>>>>>>> Bag of word  

In [12]:
import pandas as pd 

In [13]:
text = {"text":["People watch Aiyug","Aiyug watch Aiyug","People write comment ","Aiyug write comment"],"Output":[1,1,0,0] }
data =pd.DataFrame(text)
data


text  Output
0     People watch Aiyug       1
1      Aiyug watch Aiyug       1
2  People write comment        0
3    Aiyug write comment       0

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv  = CountVectorizer(lowercase=True,stop_words="english",binary=True)

In [15]:
bow =cv.fit_transform(data['text'])

In [16]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'aiyug': 0, 'write': 4, 'comment': 1}

In [17]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())


[[1 0 1 1 0]]
[[1 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


In [18]:
cv.transform(["Comment is good student and Comment is student to jaipur  "]).toarray()

array([[0, 1, 0, 0, 0]], dtype=int64)

In [19]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk

nltk.download('punkt')
nltk.download('stopwords')

text = "This is an example showing off stop word filtration."
words = word_tokenize(text)

filtered_text = [word for word in words if word.lower() not in stopwords.words('english')]
print(filtered_text)


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kumaw\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kumaw\AppData\Roaming\nltk_data...


['example', 'showing', 'stop', 'word', 'filtration', '.']


[nltk_data]   Unzipping corpora\stopwords.zip.


### N grams 

In [20]:
from nltk.util import ngrams
from nltk.tokenize import word_tokenize

text = "I love natural language processing"
tokens = word_tokenize(text)  # Tokenize into words

n = 2  # Set the N for N-grams (bigrams in this case)
bigrams = list(ngrams(tokens, n))

print(bigrams)


[('I', 'love'), ('love', 'natural'), ('natural', 'language'), ('language', 'processing')]


### Td-Idf

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "I love natural language processing",
    "Deep learning is great for NLP",
    "TF-IDF is useful in text mining"
]

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)
# print(tfidf_matrix)

feature_names = vectorizer.get_feature_names_out()  # Get the list of words (features) in the corpus

for doc_idx, doc in enumerate(tfidf_matrix.toarray()):  # Iterate over documents
    print(f"Document {doc_idx+1}:")
    for word_idx, score in enumerate(doc):  # Iterate over each word in the document
        if score > 0:  # Only print words with non-zero TF-IDF score
            print(f"  {feature_names[word_idx]}: {score:.4f}")

# 

Document 1:
  language: 0.5000
  love: 0.5000
  natural: 0.5000
  processing: 0.5000
Document 2:
  deep: 0.4234
  for: 0.4234
  great: 0.4234
  is: 0.3220
  learning: 0.4234
  nlp: 0.4234
Document 3:
  idf: 0.3899
  in: 0.3899
  is: 0.2965
  mining: 0.3899
  text: 0.3899
  tf: 0.3899
  useful: 0.3899


### Word2Vec

In [ ]:
!pip install gensim

In [ ]:
# from gensim.models import Word2Vec
# from gensim.utils import simple_preprocess
# # Sample sentences
# sentences = [
#     "Natural language processing is fun",
#     "Deep learning improves NLP",
#     "Word embeddings help understand meaning"
# ]
# tokenized_sentences = [simple_preprocess(sentence) for sentence in sentences]
# # Train Word2Vec model
# model = Word2Vec(sentences=tokenized_sentences, vector_size=50, window=5, min_count=1, workers=4)

In [11]:
from gensim.models import Word2Vec

# Sample data
sentences = [
    ['i', 'love', 'deep', 'learning'],
    ['word2vec', 'is', 'a', 'cool', 'nlp', 'technique'],
    ['nlp', 'includes', 'text', 'processing', 'and', 'modeling']
]

# Train Word2Vec model
model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)

# Get vector for a word
vector = model.wv['nlp']

# Find similar words
print(model.wv.most_similar('nlp'))


ModuleNotFoundError: No module named 'gensim'

In [10]:
# Get similar words
# print(model.wv.most_similar("nlp"))
import gensim
from gensim.models import Word2Vec
from gensim.utils import simple_preprocess
# Sample sentences
sentences = [
    "Natural language processing is fun",
    "Deep learning improves NLP",
    "Word embeddings help understand meaning"
]
tokenized_sentences = [simple_preprocess(sentence) for sentence in sentences]
# Train Word2Vec model
model = Word2Vec(sentences=tokenized_sentences, vector_size=50, window=5, min_count=1, workers=4)

ModuleNotFoundError: No module named 'gensim'

### Parts of Speech tagging 

In [1]:
import spacy

In [2]:
nlp = spacy.load('en_core_web_sm')

In [3]:
doc=nlp(u"i will google about facebook")

In [4]:
doc[0]

i

In [5]:
doc.text

'i will google about facebook'

In [6]:
doc[0].pos_

'PRON'

In [7]:
doc[0].tag_

'PRP'

In [8]:
spacy.explain("PRP")

'pronoun, personal'

In [9]:
for x in doc:
    print(x.text,"----->",x.pos_,x.tag_,spacy.explain(x.tag_))

i -----> PRON PRP pronoun, personal
will -----> AUX MD verb, modal auxiliary
google -----> VERB VB verb, base form
about -----> ADP IN conjunction, subordinating or preposition
facebook -----> PROPN NNP noun, proper singular


In [10]:
doc2=nlp(u"i left the room")
for x in doc2:
    print(x.text,"----->",x.pos_,x.tag_,spacy.explain(x.tag_))

i -----> PRON PRP pronoun, personal
left -----> VERB VBD verb, past tense
the -----> DET DT determiner
room -----> NOUN NN noun, singular or mass


In [11]:
doc2=nlp(u"to the left of the room")
for x in doc2:
    print(x.text,"----->",x.pos_,x.tag_,spacy.explain(x.tag_))

to -----> ADP IN conjunction, subordinating or preposition
the -----> DET DT determiner
left -----> NOUN NN noun, singular or mass
of -----> ADP IN conjunction, subordinating or preposition
the -----> DET DT determiner
room -----> NOUN NN noun, singular or mass


In [12]:
doc2=nlp(u"i read book on history")
for x in doc2:
    print(x.text,"----->",x.pos_,x.tag_,spacy.explain(x.tag_))

i -----> PRON PRP pronoun, personal
read -----> VERB VBP verb, non-3rd person singular present
book -----> NOUN NN noun, singular or mass
on -----> ADP IN conjunction, subordinating or preposition
history -----> NOUN NN noun, singular or mass


In [13]:
doc2=nlp(u"i have read a book on history")
for x in doc2:
    print(x.text,"----->",x.pos_,x.tag_,spacy.explain(x.tag_))

i -----> PRON PRP pronoun, personal
have -----> AUX VBP verb, non-3rd person singular present
read -----> VERB VBN verb, past participle
a -----> DET DT determiner
book -----> NOUN NN noun, singular or mass
on -----> ADP IN conjunction, subordinating or preposition
history -----> NOUN NN noun, singular or mass


In [14]:
from spacy import displacy

In [15]:
displacy.render(doc2,style='dep',jupyter=True)